// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/servicio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje básico de respuesta (lo usamos en varias partes)
type EvokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvokerResponse) Reset() {
	*x = EvokerResponse{}
	mi := &file_proto_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvokerResponse) ProtoMessage() {}

func (x *EvokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvokerResponse.ProtoReflect.Descriptor instead.
func (*EvokerResponse) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *EvokerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EvokerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvokerResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Para el Unary
type EvokerByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvokerByIdRequest) Reset() {
	*x = EvokerByIdRequest{}
	mi := &file_proto_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvokerByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvokerByIdRequest) ProtoMessage() {}

func (x *EvokerByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvokerByIdRequest.ProtoReflect.Descriptor instead.
func (*EvokerByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *EvokerByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Para el Server Streaming
type EvokersByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Ej. Buscar todos los que contengan "Mago"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvokersByNameRequest) Reset() {
	*x = EvokersByNameRequest{}
	mi := &file_proto_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvokersByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvokersByNameRequest) ProtoMessage() {}

func (x *EvokersByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvokersByNameRequest.ProtoReflect.Descriptor instead.
func (*EvokersByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *EvokersByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Para el Client Streaming (Datos de entrada)
type CreateEvokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // Validar: No vacío
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // Validar: >= 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEvokerRequest) Reset() {
	*x = CreateEvokerRequest{}
	mi := &file_proto_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEvokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEvokerRequest) ProtoMessage() {}

func (x *CreateEvokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEvokerRequest.ProtoReflect.Descriptor instead.
func (*CreateEvokerRequest) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEvokerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEvokerRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Respuesta final del Client Streaming
type CreateEvokersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvokersCount  int32                  `protobuf:"varint,1,opt,name=evokers_count,json=evokersCount,proto3" json:"evokers_count,omitempty"` // Cuántos se crearon con éxito
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEvokersResponse) Reset() {
	*x = CreateEvokersResponse{}
	mi := &file_proto_servicio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEvokersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEvokersResponse) ProtoMessage() {}

func (x *CreateEvokersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEvokersResponse.ProtoReflect.Descriptor instead.
func (*CreateEvokersResponse) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEvokersResponse) GetEvokersCount() int32 {
	if x != nil {
		return x.EvokersCount
	}
	return 0
}

func (x *CreateEvokersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_servicio_proto protoreflect.FileDescriptor

const file_proto_servicio_proto_rawDesc = "" +
	"\n" +
	"\x14proto/servicio.proto\x12\bservicio\"J\n" +
	"\x0eEvokerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"#\n" +
	"\x11EvokerByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"*\n" +
	"\x14EvokersByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"?\n" +
	"\x13CreateEvokerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"V\n" +
	"\x15CreateEvokersResponse\x12#\n" +
	"\revokers_count\x18\x01 \x01(\x05R\fevokersCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfa\x01\n" +
	"\rEvokerService\x12F\n" +
	"\rGetEvokerById\x12\x1b.servicio.EvokerByIdRequest\x1a\x18.servicio.EvokerResponse\x12N\n" +
	"\x10GetEvokersByName\x12\x1e.servicio.EvokersByNameRequest\x1a\x18.servicio.EvokerResponse0\x01\x12Q\n" +
	"\rCreateEvokers\x12\x1d.servicio.CreateEvokerRequest\x1a\x1f.servicio.CreateEvokersResponse(\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_servicio_proto_rawDescOnce sync.Once
	file_proto_servicio_proto_rawDescData []byte
)

func file_proto_servicio_proto_rawDescGZIP() []byte {
	file_proto_servicio_proto_rawDescOnce.Do(func() {
		file_proto_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_servicio_proto_rawDesc), len(file_proto_servicio_proto_rawDesc)))
	})
	return file_proto_servicio_proto_rawDescData
}

var file_proto_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_servicio_proto_goTypes = []any{
	(*EvokerResponse)(nil),        // 0: servicio.EvokerResponse
	(*EvokerByIdRequest)(nil),     // 1: servicio.EvokerByIdRequest
	(*EvokersByNameRequest)(nil),  // 2: servicio.EvokersByNameRequest
	(*CreateEvokerRequest)(nil),   // 3: servicio.CreateEvokerRequest
	(*CreateEvokersResponse)(nil), // 4: servicio.CreateEvokersResponse
}
var file_proto_servicio_proto_depIdxs = []int32{
	1, // 0: servicio.EvokerService.GetEvokerById:input_type -> servicio.EvokerByIdRequest
	2, // 1: servicio.EvokerService.GetEvokersByName:input_type -> servicio.EvokersByNameRequest
	3, // 2: servicio.EvokerService.CreateEvokers:input_type -> servicio.CreateEvokerRequest
	0, // 3: servicio.EvokerService.GetEvokerById:output_type -> servicio.EvokerResponse
	0, // 4: servicio.EvokerService.GetEvokersByName:output_type -> servicio.EvokerResponse
	4, // 5: servicio.EvokerService.CreateEvokers:output_type -> servicio.CreateEvokersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_servicio_proto_init() }
func file_proto_servicio_proto_init() {
	if File_proto_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_servicio_proto_rawDesc), len(file_proto_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_servicio_proto_goTypes,
		DependencyIndexes: file_proto_servicio_proto_depIdxs,
		MessageInfos:      file_proto_servicio_proto_msgTypes,
	}.Build()
	File_proto_servicio_proto = out.File
	file_proto_servicio_proto_goTypes = nil
	file_proto_servicio_proto_depIdxs = nil
}
