// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/servicio.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EvokerService_GetEvokerById_FullMethodName    = "/servicio.EvokerService/GetEvokerById"
	EvokerService_GetEvokersByName_FullMethodName = "/servicio.EvokerService/GetEvokersByName"
	EvokerService_CreateEvokers_FullMethodName    = "/servicio.EvokerService/CreateEvokers"
)

// EvokerServiceClient is the client API for EvokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvokerServiceClient interface {
	// 1. UNARY: Buscar un invocador por ID
	// Si no existe, devuelve error NOT_FOUND
	GetEvokerById(ctx context.Context, in *EvokerByIdRequest, opts ...grpc.CallOption) (*EvokerResponse, error)
	// 2. SERVER STREAMING: Buscar invocadores por nombre
	// El cliente manda "Merlin" y el server responde un flujo con todos los "Merlin" que encuentre
	GetEvokersByName(ctx context.Context, in *EvokersByNameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EvokerResponse], error)
	// 3. CLIENT STREAMING: Crear invocadores masivamente
	// El cliente manda un flujo de datos, el servidor los guarda y al final dice cuántos guardó
	CreateEvokers(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateEvokerRequest, CreateEvokersResponse], error)
}

type evokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEvokerServiceClient(cc grpc.ClientConnInterface) EvokerServiceClient {
	return &evokerServiceClient{cc}
}

func (c *evokerServiceClient) GetEvokerById(ctx context.Context, in *EvokerByIdRequest, opts ...grpc.CallOption) (*EvokerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvokerResponse)
	err := c.cc.Invoke(ctx, EvokerService_GetEvokerById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evokerServiceClient) GetEvokersByName(ctx context.Context, in *EvokersByNameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EvokerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EvokerService_ServiceDesc.Streams[0], EvokerService_GetEvokersByName_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EvokersByNameRequest, EvokerResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EvokerService_GetEvokersByNameClient = grpc.ServerStreamingClient[EvokerResponse]

func (c *evokerServiceClient) CreateEvokers(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateEvokerRequest, CreateEvokersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EvokerService_ServiceDesc.Streams[1], EvokerService_CreateEvokers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateEvokerRequest, CreateEvokersResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EvokerService_CreateEvokersClient = grpc.ClientStreamingClient[CreateEvokerRequest, CreateEvokersResponse]

// EvokerServiceServer is the server API for EvokerService service.
// All implementations must embed UnimplementedEvokerServiceServer
// for forward compatibility.
type EvokerServiceServer interface {
	// 1. UNARY: Buscar un invocador por ID
	// Si no existe, devuelve error NOT_FOUND
	GetEvokerById(context.Context, *EvokerByIdRequest) (*EvokerResponse, error)
	// 2. SERVER STREAMING: Buscar invocadores por nombre
	// El cliente manda "Merlin" y el server responde un flujo con todos los "Merlin" que encuentre
	GetEvokersByName(*EvokersByNameRequest, grpc.ServerStreamingServer[EvokerResponse]) error
	// 3. CLIENT STREAMING: Crear invocadores masivamente
	// El cliente manda un flujo de datos, el servidor los guarda y al final dice cuántos guardó
	CreateEvokers(grpc.ClientStreamingServer[CreateEvokerRequest, CreateEvokersResponse]) error
	mustEmbedUnimplementedEvokerServiceServer()
}

// UnimplementedEvokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEvokerServiceServer struct{}

func (UnimplementedEvokerServiceServer) GetEvokerById(context.Context, *EvokerByIdRequest) (*EvokerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvokerById not implemented")
}
func (UnimplementedEvokerServiceServer) GetEvokersByName(*EvokersByNameRequest, grpc.ServerStreamingServer[EvokerResponse]) error {
	return status.Error(codes.Unimplemented, "method GetEvokersByName not implemented")
}
func (UnimplementedEvokerServiceServer) CreateEvokers(grpc.ClientStreamingServer[CreateEvokerRequest, CreateEvokersResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateEvokers not implemented")
}
func (UnimplementedEvokerServiceServer) mustEmbedUnimplementedEvokerServiceServer() {}
func (UnimplementedEvokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeEvokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvokerServiceServer will
// result in compilation errors.
type UnsafeEvokerServiceServer interface {
	mustEmbedUnimplementedEvokerServiceServer()
}

func RegisterEvokerServiceServer(s grpc.ServiceRegistrar, srv EvokerServiceServer) {
	// If the following call panics, it indicates UnimplementedEvokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EvokerService_ServiceDesc, srv)
}

func _EvokerService_GetEvokerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvokerByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvokerServiceServer).GetEvokerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvokerService_GetEvokerById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvokerServiceServer).GetEvokerById(ctx, req.(*EvokerByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvokerService_GetEvokersByName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EvokersByNameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EvokerServiceServer).GetEvokersByName(m, &grpc.GenericServerStream[EvokersByNameRequest, EvokerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EvokerService_GetEvokersByNameServer = grpc.ServerStreamingServer[EvokerResponse]

func _EvokerService_CreateEvokers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EvokerServiceServer).CreateEvokers(&grpc.GenericServerStream[CreateEvokerRequest, CreateEvokersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EvokerService_CreateEvokersServer = grpc.ClientStreamingServer[CreateEvokerRequest, CreateEvokersResponse]

// EvokerService_ServiceDesc is the grpc.ServiceDesc for EvokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicio.EvokerService",
	HandlerType: (*EvokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvokerById",
			Handler:    _EvokerService_GetEvokerById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvokersByName",
			Handler:       _EvokerService_GetEvokersByName_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateEvokers",
			Handler:       _EvokerService_CreateEvokers_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/servicio.proto",
}
